[project]
name = 'aibtcdev-smart-contracts'
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.aibtcdev-aibtc]
path = 'src/aibtcdev-aibtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.aibtcdev-trait-v1]
path = 'src/aibtcdev-trait-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.aibtcdev-resources-v1]
path = 'src/aibtcdev-resources-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.aibtcdev-vault]
path = 'src/aibtcdev-vault.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
